### ISSUE TITLE
Noble Logo/Branding

### ISSUE THREAD

**Issue by thomasarivera** [AskADock/noble#3]
Please do work for this task in a branch called issue-3.

Create branding for the Noble website. Should get the feeling of honor, trust, and calm.

We might want to consider this color pallet:
https://images.squarespace-cdn.com/content/v1/60c64b7a673ff7171bd353d9/0c43ad4a-d84c-45e9-9eb2-b268590363fd/Asset+1.png

**Comment by rinaogino** [comment]
https://www.canva.com/design/DAGTCPxj44U/3kpa03Vy8ZPfH2ppnKC8qw/edit?utm_content=DAGTCPxj44U&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
